# Generated by Django 5.0.2 on 2024-02-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.TextField()),
                ('contact_surname', models.TextField()),
                ('contact_phone', models.IntegerField()),
                ('contact_notes', models.TextField()),
            ],
        ),
    ]
