# Generated by Django 5.0.2 on 2024-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='contact_phone',
            field=models.TextField(),
        ),
    ]
